name = "ConstrainedDynamicsVis"
uuid = "07ee0992-da0a-4409-aa8f-e0a0c9c09c30"
authors = ["Jan Bruedigam"]
version = "0.3.1"

[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
ConstrainedDynamics = "65b0d8a9-e9fd-4f02-8653-a7163c490b26"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"

[compat]
Blink = "<0.12.4, 0.12.4"
ConstrainedDynamics = "0.7.0"
CoordinateTransformations = "<0.6.1, 0.6.1"
GeometryBasics = "<0.3.8, 0.3.8"
MeshCat = "0.12.0 - 0.13.1, 0.13.2"
Rotations = "1.0"
julia = "1.4 - 1.5, 1.6"

[extras]
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "MeshCat", "SafeTestsets"]
